### ISSUE TITLE
What about adding option "-march=native"

### ISSUE THREAD

**Issue by playgithub** [Nifury/ungoogled-chromium-windows#12]
For GCC and clang, what about adding option "-march=native", which also implies "-mtune=native"?

**Comment by Nifury** [comment]
It's probably not a good idea to set `-march=native`. 
https://stackoverflow.com/questions/52653025/why-is-march-native-used-so-rarely

**Comment by playgithub** [comment]
Alright, it's not easy and conisitent.

Thanks
