### ISSUE TITLE
About chrome.packed.7z

### ISSUE THREAD

**Issue by Rusenche** [Nifury/ungoogled-chromium-windows#13]
About **chrome.packed.7z**

Hello to the developer.

While looking at https://github.com/Nifury/ungoogled-chromium-binaries/releases I came across **chrome.packed.7z** in the archive of Ungoogled Chromium.

What is the purpose of the archive _**ungoogled-chromium_95.0.4638.69-1.1_windows.zip**_ -> https://github.com/Nifury/ungoogled-chromium-binaries/releases/download/95.0.4638.69-1/ungoogled-chromium_95.0.4638.69-1.1_windows.zip added **chrome.packed.7z**?!

Is this archive **chrome.packed.7z**, placed inside **_ungoogled-chromium_95.0.4638.69-1.1_windows.zip_**, redundant and forgotten?! Besides, it is not small at all, because it is 63.5 MB.

**Comment by Nifury** [comment]
It is included according to `chrome/tools/build/win/FILES.cfg`, but you are right it is also redundant. 
Will submit a PR to fix this.
