### ISSUE TITLE
please consider 32 bit build

### ISSUE THREAD

**Issue by jacob755** [Nifury/ungoogled-chromium-windows#15]
hi please consider create  32 bit build version

thanks alot

**Comment by Nifury** [comment]
The 32-bit build has been uploaded to https://ungoogled-software.github.io/ungoogled-chromium-binaries/.

**Comment by jacob755** [comment]
> The 32-bit build has been uploaded to https://ungoogled-software.github.io/ungoogled-chromium-binaries/.

thank you so much working perfect so far

**Comment by jacob755** [comment]
update please

**Comment by jacob755** [comment]
thank you man
