### ISSUE TITLE
Will chromium v98 be supported?

### ISSUE THREAD

**Issue by playgithub** [Nifury/ungoogled-chromium-windows#17]

**Comment by playgithub** [comment]
BTW v99 is on the way, https://github.com/Eloston/ungoogled-chromium/pull/1850

**Comment by Nifury** [comment]
Yes and there is a PR for v98: https://github.com/ungoogled-software/ungoogled-chromium-windows/pull/131

I will try to keep this project up-to-date once I have some time, but I've been quite occupied recently. 😣

**Comment by playgithub** [comment]
> Yes and there is a PR for v98: [ungoogled-software#131](https://github.com/ungoogled-software/ungoogled-chromium-windows/pull/131)
> 
> I will try to keep this project up-to-date once I have some time, but I've been quite occupied recently. 😣

Thanks
