### ISSUE TITLE
Use better/alternative compression to pack the released binaries

### ISSUE THREAD

**Issue by tomasz1986** [Nifury/ungoogled-chromium-windows#18]
I'd like to ask whether it was possible to use a better or alternative compression format to pack the released binaries. For instance, the current `zip` archive of the x64 release takes about 97 MB. The very same package, when compressed with something like `7z`, can have its size reduced to as low as 67 MB, which is about 30 MB less than the current package.

It may not seem much for those with very fast Internet, but the difference is real for someone like myself who's stuck on an ~8 Mbps connection (or slower) and wants to update the browser on a dozen devices or so.

For the record, I'm talking about the binaries released under https://github.com/Nifury/ungoogled-chromium-binaries/releases, because the ones in this repository seem not to be updated anymore (and they also lack the x86 release).

**Comment by Nifury** [comment]
> and wants to update the browser on a dozen devices or so

How about updating the browser via a usb drive 😁

I'll set `skip_archive_compression` to false for the next build so that the installer size will be reduced to about 62MB.

**Comment by tomasz1986** [comment]
Thank you 🙂.

I've checked the new installers, and it seems the `chrome.7z` archive included inside them has exactly the same content as the other zip archives, just packed with the better 7z compression. Is this correct?

If that's the case, then I'll probably just switch to downloading the installers and then unpack them to get the files this way 😉.

**Comment by Nifury** [comment]
Yes that should be the case.
