### ISSUE TITLE
Which branch should I use for version 93.0.4577.82?

### ISSUE THREAD

**Issue by playgithub** [Nifury/ungoogled-chromium-windows#2]
I've found both branch is updated for version 93.0.4577.82,
and branch `v92.0.4515.131` is newer than branch `master`.

Which branch should I use for version 93.0.4577.82?
I've found two differences for patches in the two branches:
- `windows-fix-building-without-safebrowsing.patch` are different
- There is `patches/my` in branch `master` but not in branch `v92.0.4515.131`

BTW, I've tried to upgrade to 93.0.4577.82 before I saw your upgrade, it's not easy for me, thanks.

**Comment by Nifury** [comment]
`v92.0.4515.131` should be used for v93. Appearently using the version number as a branch name is a bad idea. However, there is an open PR so I cannot rename the branch until the PR is closed/merged. 

The only difference between `windows-fix-building-without-safebrowsing.patch` is that the v92 branch contains a fix for the download UI. 

`patches/my` contains patches that I'd like to have, but they may not be for everyone.

**Comment by playgithub** [comment]
v94.0.4606.71 is only in the master branch, has download UI been fixed in v94.0.4606.71?

**Comment by Nifury** [comment]
Yes, but you might want to remove patches in `patches/my` if you intend to use the master branch.
