### ISSUE TITLE
Why introduce `esbuild`?

### ISSUE THREAD

**Issue by playgithub** [Nifury/ungoogled-chromium-windows#20]
I've checked `https://github.com/teeminus/ungoogled-chromium-windows/blob/update_100.0.4896.60/build.py`,
no `esbuild` there.

Without hash checking for `esbuild`, how to make sure it's ok?

**Comment by Nifury** [comment]
https://github.com/ungoogled-software/ungoogled-chromium-windows/pull/139#issuecomment-1086168275
it doesn't compile without esbuild. 



> Without hash checking for `esbuild`, how to make sure it's ok?

It depends on how you define ok. If you just want to check if the file is corrupted, there is no need because a corrupted file won't be unzipped properly.

**Comment by playgithub** [comment]
I've tried https://github.com/teeminus/ungoogled-chromium-windows/blob/update_100.0.4896.60/build.py,
it fails because of lack of `esbuild.exe`.

Why not put `esbuild` in `downloads.ini`?

**Comment by Nifury** [comment]
Each chromium build requires a specific version of esbuild. Putting it in `downloads.ini` means it may have to be updated frequently.

**Comment by playgithub** [comment]
By looking into `build.py`, it downloads `esbuild` at `chrome-infra-packages.appspot.com`, and it is an offical site of google, so it secure.

I think a python script to update `download.ini` automatically is also fine.

Thanks

**Comment by teeminus** [comment]
I know it's a manual step which needs to be documented and double checked before merging new releases into master, but why don't we add the required esbuild version manually to the build.py script (or wherever it belongs)?

**Comment by Nifury** [comment]
We surely can, but it's one less thing to worry about if we can fetch the required version automatically.

**Comment by teeminus** [comment]
In your esbuild MR you spoke about using exec because you don't want to add external dependencies. If it's an python import, can't those dependencies be automatically installed? (I'm sorry if that's a dumb question, I know close to nothing about Python)

**Comment by Nifury** [comment]
Unfortunately it cannot. It would cause ambiguity and possibly safety issues. 
Is there a language that supports this feature?

**Comment by teeminus** [comment]
I don't know if there is a programming language that is capable of doing this.

Anyways, your modification for parsing the DEPS file and downloading esbuild in the build.py works like a charm, good job 👍
