### ISSUE TITLE
Is admin priviledge mandatory when doing with ninja now?

### ISSUE THREAD

**Issue by playgithub** [Nifury/ungoogled-chromium-windows#21]
As I remeber, for old versions, it's only mandatory for admin priviledge when extracting because of `mklink`,
and I split `build.py` to 2 parts, one is for `ninja` only, which doesn't need admin priviledge.
For chromium version 100, when doing with `ninja`, it also needs admin priviledge, is it safe?
```
λ py build-with-ninja.py
D:\ungoogled-chromium-windows\build\src>call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat" >nul

D:\ungoogled-chromium-windows\build\src>set DEPOT_TOOLS_WIN_TOOLCHAIN=0

D:\ungoogled-chromium-windows\build\src>"third_party\ninja\ninja.exe" "-C" "out\Default" "-j" "4" "chrome" "chromedriver" "mini_installer"
ninja: Entering directory `out\Default'
[21/47545] ACTION //sandbox/win:set_appcontainer_acls(//build/toolchain/win:win_clang_x64)
FAILED: obj/sandbox/win/acls.stamp
C:/Users/aaa/AppData/Local/Programs/Python/Python310/python3.exe ../../build/win/set_appcontainer_acls.py --stamp=obj/sandbox/win/acls.stamp --dir=.
ERROR:root:Failed to retrieve existing ACLs for directory D:\ungoogled-chromium-windows\build\src\out\Default
ERROR:root:Command output: b'D:\\ungoogled-chromium-windows\\build\\src\\out\\Default: Access is denied.\r\nSuccessfully processed 0 files; Failed processing 1 files\r\n'
[24/47545] CXX obj/third_party/angle/translator_gl_d3d_only/RemoveUnreferencedVariables.obj
ninja: build stopped: subcommand failed.

D:\ungoogled-chromium-windows\build\src>exit
Traceback (most recent call last):
  File "D:\ungoogled-chromium-windows\build-only.py", line 122, in <module>
    main()
  File "D:\ungoogled-chromium-windows\build-only.py", line 116, in main
    _run_build_process('third_party\\ninja\\ninja.exe', '-C', 'out\\Default',
  File "D:\ungoogled-chromium-windows\build-only.py", line 64, in _run_build_process
    subprocess.run(('cmd.exe', '/k'),
  File "C:\Users\aaa\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '('cmd.exe', '/k')' returned non-zero exit status 1.
```

**Comment by Nifury** [comment]
https://github.com/chromium/chromium/blob/494bf1e595e8ec1560a1c18c6eb55e9851208dc1/docs/design/sandbox.md#less-privileged-app-container-lpac
https://github.com/chromium/chromium/blob/494bf1e595e8ec1560a1c18c6eb55e9851208dc1/sandbox/win/BUILD.gn#L228-L240

Looks safe to me.

**Comment by playgithub** [comment]
For this function, it should be safe.
But when the build run with admin priviledge, how to ensure safety, because it can do other things with admin priviledge.

**Comment by Nifury** [comment]
You can build Chromium in an isolated environment, such as virtual machines or GitHub Actions. 

In fact, a program can still do lots of things even without admin privilege. If you don't trust the script, maybe it's not a good idea to use what it generates (i.e., Chromium).

**Comment by playgithub** [comment]
I trust the ungoogled scripts.
The original chromium (i.e. without ungoogled patches) also needs admin, right?
If yes, I can trust it.

**Comment by Nifury** [comment]
I don't know, but I think it requires admin privilege, judging from `set_appcontainer_acls.py` script. 

Anyway, I'm not saying you shouldn't be suspicious of the admin privilege - it is a good practice to run programs from unknown sources in an isolated environment. It's just unfortunate that Windows doesn't have a lightweight virtual environment like Docker.
