### ISSUE TITLE
Fix compiler warnings

### ISSUE THREAD

**Issue by playgithub** [Nifury/ungoogled-chromium-windows#3]
## Warning

clang-cl: warning: unknown argument ignored in clang-cl: '-fno-ident' [-Wunknown-argument]

## Solve

Delete the 3 lines below in `src\build\config\compiler\BUILD.gn`

line 315 to 317
```cpp
if (!is_win || is_clang) {
cflags += [ "-fno-ident" ]
}
```

**Comment by Nifury** [comment]
Hopefully it will be introduced in LLVM 13. 
https://github.com/llvm/llvm-project/commit/83feaa36ad53ce93ed808169d3316ed757703e47
